# Generated by Django 4.2.7 on 2023-11-23 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sharing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="message",
        ),
        migrations.AddField(
            model_name="message",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="audio_messages/"),
        ),
        migrations.AddField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
